### ISSUE TITLE
NoRouteToHostException

### ISSUE THREAD

**Issue by mudphone** [ragnard/redis-clojure#7]
Hi Ragnard,

I have another exception that I'm seeing (below).  After adding about 16328 members to a set, the stack trace shows up.  I believe it has to do with opening too many sockets on the Redis server.

The code I'm using to reproduce this exception is here:
http://gist.github.com/276511

Any suggestions appreciated.

Thanks,
Kyle

adding member # 100000
... counts down ...
adding member # 83672
Exception in thread "main" java.net.NoRouteToHostException: Can't assign requested address (test_redis.clj:0)
    at clojure.lang.Compiler.eval(Compiler.java:4617)
    at clojure.lang.Compiler.load(Compiler.java:4931)
    at clojure.lang.Compiler.loadFile(Compiler.java:4898)
    at clojure.main$load_script__6637.invoke(main.clj:210)
    at clojure.main$init_opt__6640.invoke(main.clj:215)
    at clojure.main$initialize__6650.invoke(main.clj:243)
    at clojure.main$null_opt__6672.invoke(main.clj:268)
    at clojure.main$legacy_script__6687.invoke(main.clj:299)
    at clojure.lang.Var.invoke(Var.java:359)
    at clojure.main.legacy_script(main.java:32)
    at clojure.lang.Script.main(Script.java:20)
Caused by: java.net.NoRouteToHostException: Can't assign requested address
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
    at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:432)
    at java.net.Socket.connect(Socket.java:525)
    at java.net.Socket.connect(Socket.java:475)
    at java.net.Socket.<init>(Socket.java:372)
    at java.net.Socket.<init>(Socket.java:186)
    at redis.internal$connect_to_server__44.invoke(internal.clj:32)
    at redis.internal$with_server_STAR___49.invoke(internal.clj:41)
    at user$add_random_value_to_set__588.invoke(test_redis.clj:38)
    at user$create_large_set__594.invoke(test_redis.clj:45)
    at user$eval__600.invoke(test_redis.clj:50)
    at clojure.lang.Compiler.eval(Compiler.java:4601)
    ... 10 more

**Comment by ragnard** [comment]
Thanks for the report, I'll take a look as soon as possible.

**Comment by mudphone** [comment]
Hi Ragnar, 

I think I have since found that my use of the library was the cause of the NoRouteToHostException.  I was simply opening too many sockets on the same host (faster than they could be recovered).  I have since done tests in which I place all the create key calls in a single "redis/with-server" form and that works fine.  I was able to create a million keys without errors in a singe with-server call.

I don't know if you've had time to check out the issue I posted a while back.  I'm still seeing that one.  I get a "could not read correct number of bytes" back from the redis-clojure library.  I'm not sure if that's related to this socket use problem that I'm causing by creating so many connections.  But, what is strange is that it is intermittent.

Let me know if I can help with any additional info.

**Comment by mudphone** [comment]
I should close this one issue since it was really a user error.

**Comment by mudphone** [comment]
Trying to close again.

**Comment by ragnard** [comment]
I'll close it. Suspected it might be a user error. Thanks anyway though, all feedback is welcome!
